swayimg.set_appid("swayimg")
swayimg.viewer.enable_loop(false)
swayimg.viewer.set_window_background(0xc13e4040)
swayimg.set_mode("viewer")
-- swayimg.viewer.set_default_scale("optimal")
swayimg.viewer.set_default_scale("fit")
-- 初次打开时并没有按照`fit`来缩放。
swayimg.on_window_resize(function()
  swayimg.viewer.set_fix_scale("fit")
end)
-- swayimg.gallery.enable_embedded_thumb(true)
swayimg.gallery.enable_pstore(true)
-- swayimg.gallery.enable_preload(true)
swayimg.gallery.set_aspect("fill")
swayimg.gallery.set_thumb_size(300)
swayimg.imagelist.enable_adjacent(true)

swayimg.text.hide()
swayimg.text.set_font("monospace")
swayimg.text.set_size(26)
swayimg.text.set_foreground(0xfff0c30f)
swayimg.text.set_background(0x30000000)

-- swayimg.text.set_shadow(0x300090)




swayimg.viewer.on_key("k", function()
  swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_key("j", function()
  swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_key("r", function()
  swayimg.viewer.rotate(90)
end)
swayimg.viewer.on_key("f", function()
  swayimg.viewer.flip_horizontal()
end)
swayimg.viewer.on_key("q", function()
  swayimg.exit()
end)
swayimg.viewer.on_key("g", function()
  swayimg.set_mode("gallery")
end)
swayimg.viewer.on_key("o", function()
  swayimg.set_mode("gallery")
end)
swayimg.viewer.on_key("i", function()
  if swayimg.text.visible() then
    swayimg.text.hide()
  else
    swayimg.text.show()
  end
end)

swayimg.gallery.on_key("q", function()
  swayimg.exit()
end)
swayimg.gallery.on_key("h", function()
  swayimg.gallery.switch_image("left")
end)
swayimg.gallery.on_key("l", function()
  swayimg.gallery.switch_image("right")
end)
swayimg.gallery.on_key("k", function()
  swayimg.gallery.switch_image("up")
end)
swayimg.gallery.on_key("j", function()
  swayimg.gallery.switch_image("down")
end)
swayimg.gallery.on_key("o", function()
  swayimg.set_mode("viewer")
end)
