theme = "catppuccin_mocha_nb"
[editor]
mouse = false
auto-format = true
# completion-timeout = 100
# completion-trigger-len = 1
# completion-auto-select = true
word-completion = { enable = false, trigger-length = 3 }
inline-completion-auto-trigger = false

[editor.inline-diagnostics]
# cursor-line = "disable"
# other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-ignore = true

[editor.terminal]
command = "kitty"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
nnbsp = "␣"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
nbsp = "all"
newline = "all"
nnbsp = "all"
space = "none"
tab = "all"

[keys.insert]
C-s = [":wa", "save_selection"]
# esc = [":run-shell-command ~/nixos/home/misc/scripts/setrimeasciimode.sh true", "normal_mode"]
"A-l" = "inline_completion_accept"
"C-x" = ["inline_completion_trigger", "completion"]
"A-j" = "inline_completion_next"
"A-k" = "inline_completion_prev"

[keys.normal]
C-s = [":w", "save_selection"]
C-c = ":sh wl-copy '%<buffer_name>:L%<selection_line_start>-L%<selection_line_end>'"
C-r = ":reload-all"
# esc = [":run-shell-command ~/nixos/home/misc/scripts/setrimeasciimode.sh true"]

