pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#161311"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#342f2e"
  readonly property color inverse_primary: "#7b5546"
  readonly property color inverse_surface: "#eae1de"
  readonly property color on_background: "#eae1de"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#47291c"
  readonly property color on_primary_container: "#2d1308"
  readonly property color on_primary_fixed: "#2f1409"
  readonly property color on_primary_fixed_variant: "#613e30"
  readonly property color on_secondary: "#3d2d26"
  readonly property color on_secondary_container: "#faded4"
  readonly property color on_secondary_fixed: "#261813"
  readonly property color on_secondary_fixed_variant: "#55433c"
  readonly property color on_surface: "#eae1de"
  readonly property color on_surface_variant: "#d5c3bd"
  readonly property color on_tertiary: "#123636"
  readonly property color on_tertiary_container: "#001f1f"
  readonly property color on_tertiary_fixed: "#002020"
  readonly property color on_tertiary_fixed_variant: "#2b4c4d"
  readonly property color outline: "#9d8d88"
  readonly property color outline_variant: "#504440"
  readonly property color primary: "#edbca9"
  readonly property color primary_container: "#c99b89"
  readonly property color primary_fixed: "#ffdbce"
  readonly property color primary_fixed_dim: "#edbca9"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#dbc1b8"
  readonly property color secondary_container: "#57453e"
  readonly property color secondary_fixed: "#f8ddd3"
  readonly property color secondary_fixed_dim: "#dbc1b8"
  readonly property color shadow: "#000000"
  readonly property color surface: "#161311"
  readonly property color surface_bright: "#3d3836"
  readonly property color surface_container: "#231f1d"
  readonly property color surface_container_high: "#2d2927"
  readonly property color surface_container_highest: "#383432"
  readonly property color surface_container_low: "#1f1b19"
  readonly property color surface_container_lowest: "#110d0c"
  readonly property color surface_dim: "#161311"
  readonly property color surface_tint: "#edbca9"

  readonly property color surface_variant: "#504440"
  readonly property color tertiary: "#a9cdcd"
  readonly property color tertiary_container: "#89acac"
  readonly property color tertiary_fixed: "#c5e9e9"
  readonly property color tertiary_fixed_dim: "#a9cdcd"

  function withAlpha(color: color, alpha: real): color {
    return Qt.rgba(color.r, color.g, color.b, alpha)
  }
}
