pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#11131a"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#2e3038"
  readonly property color inverse_primary: "#005ac1"
  readonly property color inverse_surface: "#e1e2eb"
  readonly property color on_background: "#e1e2eb"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#002e69"
  readonly property color on_primary_container: "#000000"
  readonly property color on_primary_fixed: "#001a41"
  readonly property color on_primary_fixed_variant: "#004494"
  readonly property color on_secondary: "#193057"
  readonly property color on_secondary_container: "#dae4ff"
  readonly property color on_secondary_fixed: "#001a41"
  readonly property color on_secondary_fixed_variant: "#31466f"
  readonly property color on_surface: "#e1e2eb"
  readonly property color on_surface_variant: "#c2c6d5"
  readonly property color on_tertiary: "#4e2600"
  readonly property color on_tertiary_container: "#000000"
  readonly property color on_tertiary_fixed: "#2f1400"
  readonly property color on_tertiary_fixed_variant: "#6f3800"
  readonly property color outline: "#8c909f"
  readonly property color outline_variant: "#424753"
  readonly property color primary: "#adc6ff"
  readonly property color primary_container: "#4d8efe"
  readonly property color primary_fixed: "#d8e2ff"
  readonly property color primary_fixed_dim: "#adc6ff"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#b1c6f7"
  readonly property color secondary_container: "#344972"
  readonly property color secondary_fixed: "#d8e2ff"
  readonly property color secondary_fixed_dim: "#b1c6f7"
  readonly property color shadow: "#000000"
  readonly property color surface: "#11131a"
  readonly property color surface_bright: "#363940"
  readonly property color surface_container: "#1d2026"
  readonly property color surface_container_high: "#272a31"
  readonly property color surface_container_highest: "#32353c"
  readonly property color surface_container_low: "#191b22"
  readonly property color surface_container_lowest: "#0b0e15"
  readonly property color surface_dim: "#11131a"
  readonly property color surface_tint: "#adc6ff"

  readonly property color surface_variant: "#424753"
  readonly property color tertiary: "#ffb780"
  readonly property color tertiary_container: "#db760f"
  readonly property color tertiary_fixed: "#ffdcc4"
  readonly property color tertiary_fixed_dim: "#ffb780"

  function withAlpha(color: color, alpha: real): color {
    return Qt.rgba(color.r, color.g, color.b, alpha)
  }
}
