anchor_to_edges = true
position = "top"
height = 30
icon_theme = "Paper"

[margin]
top = 5
bottom = 5
left = 2
right = 2

[[start]]
type = "clock"

[[start]]
type = "workspaces"
sort = "added"
on_click_right = '''niri msg windows | ~/nixos/home/misc/scripts/merge_window_info.sh | fuzzel -d | cut -d '/' -f1 | xargs -I {} niri msg action focus-window --id {}'''

[start.name_map]
NETW = " NETW  "
CODE = " CODE  "
CHAT = " CHAT  "
GAME = " GAME  "
5 = " TEMP  "
# https://unicodes.jessetane.com/%EF%89%93

[[start]]
type = "focused"
show_icon = false
[start.truncate]
mode = "end"
max_length = 100

[[end]]
type = "music"
player_type = "mpris"
format = "{title} / {artist}"

[end.truncate]
mode = "end"
max_length = 80

[end.icons]
play = ""
pause = ""

[[end]]
type = 'sys_info'
format = [
    "  {net_down#k@wlp37s0:3}/{net_up#k@wlp37s0:2}k",
    "  {cpu_percent}",
    "  {memory_used#G:2.0}",
    "  {disk_used#G@/}",
]
on_click_right = '''ghostty -e btop'''
# 

[end.interval]
cpu = 1
disks = 300
memory = 30
networks = 3
# temps = 5

[[end]]
type = "volume"
format = "  {percentage}"
max_volume = 100

[[end]]
type = "custom"
class = "brightness"

[[end.bar]]
type = "label"
label = ""
class = "brightness-label"

[[end.bar]]
type = "script"
class = "brightness-value"
cmd = "~/nixos/home/misc/scripts/ironbar-ddc-module.sh"
mode = "watch"
interval = 0
on_scroll_up = '''echo "+" > /tmp/ironbar-ddc-module-rx'''
on_scroll_down = '''echo "-" > /tmp/ironbar-ddc-module-rx'''
on_click_left = '''echo "min" > /tmp/ironbar-ddc-module-rx'''
on_click_right = '''echo "max" > /tmp/ironbar-ddc-module-rx'''

[end.icons]
volume_high = "󰕾"
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"

[[end]]
type = "tray"
icon_size = 16
prefer_theme_icons = true
